//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreppiMeteo.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreppiMeteo.Texts.TextsResource", typeof(TextsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudiness.
        /// </summary>
        internal static string Cloudiness {
            get {
                return ResourceManager.GetString("Cloudiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT LOCATION.
        /// </summary>
        internal static string DefaultLoc {
            get {
                return ResourceManager.GetString("DefaultLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Francesco Buffetti.
        /// </summary>
        internal static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew Point.
        /// </summary>
        internal static string DewPoint {
            get {
                return ResourceManager.GetString("DewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels Like.
        /// </summary>
        internal static string FeelsLike {
            get {
                return ResourceManager.GetString("FeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the language you have set is not among those supported, the app will be shown in English..
        /// </summary>
        internal static string LangDetail {
            get {
                return ResourceManager.GetString("LangDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app automatically reveals the system language by setting the language accordingly..
        /// </summary>
        internal static string LangExplain {
            get {
                return ResourceManager.GetString("LangExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location doesn&apos;t exist.
        /// </summary>
        internal static string LocNotFound {
            get {
                return ResourceManager.GetString("LocNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is not valid.
        /// </summary>
        internal static string LocNotValid {
            get {
                return ResourceManager.GetString("LocNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location saved.
        /// </summary>
        internal static string LocSaved {
            get {
                return ResourceManager.GetString("LocSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March, 2023.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next 48 hours.
        /// </summary>
        internal static string Next48 {
            get {
                return ResourceManager.GetString("Next48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next days.
        /// </summary>
        internal static string NextDays {
            get {
                return ResourceManager.GetString("NextDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the location.
        /// </summary>
        internal static string PlaceHolder {
            get {
                return ResourceManager.GetString("PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        internal static string Pop {
            get {
                return ResourceManager.GetString("Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read less &lt;.
        /// </summary>
        internal static string ReadLess {
            get {
                return ResourceManager.GetString("ReadLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more &gt;.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search locality.
        /// </summary>
        internal static string SearchLoc {
            get {
                return ResourceManager.GetString("SearchLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set geolocalization as default.
        /// </summary>
        internal static string SetGeo {
            get {
                return ResourceManager.GetString("SetGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success1 {
            get {
                return ResourceManager.GetString("Success1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV Index.
        /// </summary>
        internal static string UvIndex {
            get {
                return ResourceManager.GetString("UvIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View supported languages here.
        /// </summary>
        internal static string ViewLang {
            get {
                return ResourceManager.GetString("ViewLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Gust.
        /// </summary>
        internal static string WindGust {
            get {
                return ResourceManager.GetString("WindGust", resourceCulture);
            }
        }
    }
}
